### ISSUE TITLE
Add a .CFF file

### ISSUE THREAD

**Issue by scrunguss** [mazpie/vime-pytorch#28]
Hi, 

First of all, this repo is a lifesaver (I have a week left to finish my dissertation and I needed to implement VIME-PPO with no idea how haha). Would it be possible for you to add a .CFF file so I can cite this repository correctly in my work? 

Thanks in advance

**Comment by mazpie** [comment]
Hi,

Glad to hear this repo turned out to be helpful for you!

I added a .CFF file for citing purposes. Feel free to share :)

**Comment by scrungus** [comment]
great, thank you :)
